name: 'Build and Push Docker Image'
description: 'Builds a Docker image and pushes it to a registry'

inputs:
  image-name:
    description: 'Name of the Docker image'
    required: true
  tag:
    description: 'Tag for the Docker image'
    required: true
  dockerfile:
    description: 'Path to the Dockerfile'
    required: false
    default: 'Dockerfile'
  context:
    description: 'Docker build context'
    required: false
    default: '.'
  registry:
    description: 'Docker registry URL'
    required: true
  username:
    description: 'Username for Docker registry'
    required: true
  password:
    description: 'Password for Docker registry'
    required: true
  args:
    description: 'args for Docker build'
    required: false
    default: ''

runs:
  using: composite
  steps:
    - name: get secrets...
      shell: |
        pwd

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Registry
      uses: docker/login-action@v1
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}

    - name: Build and Push Docker image
      uses: docker/build-push-action@v2
      with:
        context: ${{ inputs.context }}
        file: ${{ inputs.dockerfile }}
        push: true
        tags: ${{ inputs.registry }}/${{ inputs.image-name }}:${{ inputs.tag }}
        build-args: ${{ inputs.args }}